name: zapmanejo-cleanbackend
services:
- name: backend
  git:
    repo_clone_url: https://github.com/YOUR_USERNAME/zapmanejo-cleanbackend.git
  environment_slug: go
  build_command: go mod tidy && go build -o zapmanejo main.go
  run_command: ./zapmanejo
  instance_count: 1
  instance_size_slug: basic-xs
  http_port: 8080
  envs:
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    value: postgres://doadmin:AVNS__rgcE7L7XWSpfnPpEhK@zapmanejobackend2-do-user-20437728-0.g.db.ondigitalocean.com:25060/defaultdb?sslmode=require
  - key: JWT_SECRET
    scope: RUN_AND_BUILD_TIME
    value: zapmanejo2025supersecretjwt
  - key: WHATSAPP_NUMBER
    scope: RUN_AND_BUILD_TIME
    value: 15616520911
  - key: WHATSAPP_VERIFY_TOKEN
    scope: RUN_AND_BUILD_TIME
    value: zapmanejo2025verifytoken2025
  - key: PORT
    scope: RUN_AND_BUILD_TIME
    value: 8080
  - key: LIFETIME_TOTAL
    scope: RUN_AND_BUILD_TIME
    value: 200
